title: "Return" # your site title
author: wookgodsun
email: koownusmim@gmail.com

description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wookgodsun.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  wookgodsun # replace with your_github_username or comment to remove link from footer
instagram_username: wo0kgod # replace with your_instagram_username or comment to remove link from footer
social:
  name: shun kim
  links:

disqus:
  shortname: wookgodsun # to enable comments replace with your_disqus_shortname

navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  "KoreaUniversity CS 14" 

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
